name: Test and Lint

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Zero65 workflow template
      uses: Zero65Tech/config@master
      with:
        template: main.yml

    env:
      GITHUB_TOKEN: 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
