name: indian-stock-market workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Zero65 workflow template
      with:
        repository: Zero65Tech/playground
        ref: master
      uses: actions/checkout@v2
    - name: Install dependencies
      run: node -v
