name: Test and Lint

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Zero65 workflow template
      uses: https://github.com/Zero65Tech/config.git@master
      with:
        template: main.yml
