name: Test and Lint

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Zero65 workflow template
      uses: actions/checkout@v2
      with:
        repository: Zero65Tech/playground
        ref: master

