name: Test and Lint

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Zero65 workflow template
      uses: actions/checkout@v2
      with:
        repository: Zero65Tech/config
        token: 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
        ref: master

