name: npm publish

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    uses: Zero65Tech/github-workflows/.github/workflows/npm-publish.yaml@master
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
