name: Zero65Tech

on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: Zero65Tech/github-workflows/.github/workflows/npm-publish.yaml@master
    with:
      NODE_VERSION: '22' # 22.12.0
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
