name: Publish Node.js Package

on:
  push:
    branches:
      - test

jobs:
  publish-npm:
    uses: Zero65Tech/github-workflows/npm-publish.yaml
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
