name: Zero65Tech

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    uses: Zero65Tech/github-workflows/.github/workflows/build-and-commit.yaml@master
  test:
    needs: build
    uses: Zero65Tech/github-workflows/.github/workflows/npm-test.yaml@master
